### ISSUE TITLE
Latest project updates

### ISSUE THREAD

**Issue by DrLeturc** [HyperAgents/hmas#166] opened 2023-09-15 13:24 UTC
Hi everyone, a lot has happened on git since this summer !

We should give an update in order to validate and close together the initial milestone opened during the last plenary.
I recall that the initial milestone consisted in publishing the second version of the ontology :

   * organization and regulation (V1),
   * interaction (V1),
   * updates on the core (V2).
   * All issues related to the v2 vocabulary must have been addressed and the PR must have been voted and accepted.

For the vocabulary, we accepted the following terms : (if update, please tell us in this issue these updates!)
Interaction V1 :

  *  Behavior Execution
  *  Action Execution
  *  Input
  *  has input
  * Signifies

Two motivating scenarios :

  *  a2e
  *  a2a

Regulation V1 :

*    RoleMemberShip
*    Group
*    Facility
*    OrganizationalValue
*    Role
*    Mission
*    providesRole
*    proposesMission
*    proposesFacility
*    hasOrganizationalValue
*    isRoleMembershipOf
*    isRoleMembershipFor
*    isRoleMembershipIn
*    hasMembershipRelation
*    isSubGroupOf
*    hasGroupRelation
*    isStructuredBy
*    structures

New terms in the Core :

 *   isMemberOf
 *   isMaterialOf
 *   isExposedIn
 *   Signifier ++ (introduction of skos:concept for Affordance)

Recent updates :

 *   Removed rdfs:subClassOf Artifact ;
 *   Update Workspace's definition ;
 *   Removed Disjointness between HMASPlatform, Workspace , Agent, Artifact and Signifier ;
 *   The HyperAgent's repository is now public !

The next Heartbeat meeting should discuss about the following issues and we should find an agreement on issues :
https://github.com/HyperAgents/hmas/issues/112
https://github.com/HyperAgents/hmas/issues/138
https://github.com/HyperAgents/hmas/pull/136
https://github.com/HyperAgents/hmas/pull/164

**Comment by gnardin** [comment] 2023-09-15 14:36
In the Regulation ontology

1. we made small changes to the label of a Class and Properties initially proposed as follows
    - `RoleMembership` -> `Membership`
    - `isRoleMembershipOf` -> `isMembershipOf`
    - `isRoleMembershipFor` -> `isMembershipFor`
    - `isRoleMembershipIn` -> `isMembershipIn`
    - `hasMembershipRelation` -> `hasMembershipRelationshipWith`

2. We removed the `hasGroupRelation` property because we identified that the same thing can be represented using the `hasMembershipRelationshipWith` property.

**Comment by FabienGandon** [comment] 2023-09-16 11:31
I have merged the branch " contributors metadata in the ontologies " and closed the PR #164 ; I also deleted the branch afterward.

**Comment by FabienGandon** [comment] 2023-09-18 09:24
I agree with the analysis of @DrLeturc and I beleive that Core v2 and Interaction V1 and Regulation V1 should be released before the 29/09/2023 as we have very few issues left open.

**Comment by NicoRobertIn** [comment] 2023-09-18 12:59
About the needed terms for the current milestone here is a summary of where is each term:

| Module | Terms | In master? | In another branch? | Any other status? |
| --- | --- | --- | --- | --- |
| Interaction V1 | BehaviorExecution |  | scenario-manufacturing-discover-behavior-specs |  |
|  | ActionExecution |  | scenario-manufacturing-discover-behavior-specs |  |
|  | Input |  | scenario-manufacturing-discover-behavior-specs |  |
|  | hasInput |  | scenario-manufacturing-discover-behavior-specs |  |
|  | signifies |  | scenario-manufacturing-discover-behavior-specs |  |
| Regulation v1 | Membership |  | scenario-logistics-structure-organization |  |
|  | Group |  | scenario-logistics-structure-organization |  |
|  | Facility | Yes |  |  |
|  | OrganizationalValue | Yes |  |  |
|  | Role | Yes |  |  |
|  | Mission | Yes |  |  |
|  | providesRole | Yes |  |  |
|  | proposesMission | Yes |  |  |
|  | proposesFacility | Yes |  |  |
|  | hasOrganizationalValue | Yes |  |  |
|  | isMembershipOf |  | scenario-logistics-structure-organization |  |
|  | isMembershipFor |  | scenario-logistics-structure-organization |  |
|  | isMembershipIn |  | scenario-logistics-structure-organization |  |
|  | hasMembershipRelationshipWith |  | scenario-logistics-structure-organization |  |
|  | isSubGroupOf |  | scenario-logistics-structure-organization |  |
|  | hasGroupRelation |  |  | Removed from ontology (see @gnardin comment |
|  | isStructuredBy |  | scenario-logistics-structure-organization |  |
|  | structures |  | scenario-logistics-structure-organization |  |
| Core v2 | isMemberOf | Yes |  |  |
|  | isMaterialOf | Yes |  |  |
|  | isExposedIn | Yes |  |  |
|  | Signifier ++ (introduction of skos:concept for Affordance) | Yes |  |  |


About the scenarii I will come back to you later

**Comment by NicoRobertIn** [comment] 2023-09-18 14:06
After some check about the existing scenarii, here is a list of what is not merged yet:

- discover-behavior-specifications (in scenario-manufacturing-discover-behavior-specs)
    - modelet, ABoxes and CQs implemented
- safety-rules-wrt-behaviors (in safety-rules-wrt-behaviors)
    - modelet and ABoxes seem to be implemented, Q1 also
    - Q8 and Q9 are still to be implemented
- safety-rules (also in scenario-manufacturing-discover-behavior-specs)
    - modelet, ABoxes, and all of the 11 CQs are implemented
- misinformation-in-databases (in domain-tackling-online-disinformation)
    - modelet/ABoxes/2 CQs are implemented
- tackling-online-disinformation/join-organization
    - 7 CQs typed down and a dataset is there
    - no modelet or sparQL CQ implementation to be found
- tackling-online-disinformation/create-organization
    - 6 CQs typed down and a dataset is there
    - no modelet or SparQL CQ implementation to be found

**Comment by gnardin** [comment] 2023-09-18 14:12
@NicoRobertIn The `scenario-logistics-structure-organization` scenario is still not merged to the `master` yet. Shouldn't it appear on this list?

**Comment by FabienGandon** [comment] 2023-09-18 14:52
Thanks @NicoRobertIn this recap is exactly what I wanted from you! This confirms that if we make the PR for all branches and proceed with the merge we have our three release versions. May I ask @danaivach and @gnardin to make sure we have all the needed PR open with, for each of them, at least one reviewer from each project partner ?

**Comment by gnardin** [comment] 2023-09-18 14:59
@FabienGandon I confirm the open PR #165 contains the agreed Regulation v1 terms definition to be merged into the `master` branch. I also confirm I have assigned one reviewer from each project partner to the PR. I am waiting comments and approval to finalize the PR and proceed with the merge.

**Comment by danaivach** [comment] 2023-09-21 13:23
@FabienGandon, I confirm the above related to Interaction v1.

**Comment by FabienGandon** [comment] 2023-10-03 16:41
As per answers the issue is covered by the latest pull requests and merge

**Closed by FabienGandon** 2023-10-03 16:41 UTC
Labels: high priority
